Repository jenkins-x/bdd-jx, pull requests merged in 2019-11, with the labels that each got.

#87 test: add cypress smoke test to UI tests
  jenkins-x.yml
  test/suite/apps/ui-smoke/.npmrc
  test/suite/apps/ui-smoke/cypress.json
  test/suite/apps/ui-smoke/cypress/integration/smoke.spec.js
  test/suite/apps/ui-smoke/cypress/plugins/index.js
  test/suite/apps/ui-smoke/cypress/support/commands.js
  test/suite/apps/ui-smoke/cypress/support/index.js
  test/suite/apps/ui-smoke/package-lock.json
  test/suite/apps/ui-smoke/package.json
  test/suite/apps/ui-smoke/run.sh
  test/suite/apps/ui.go
Labels: approved, size/XXL

#93 fix: so that BDD tests actually run rather than just do a build ;)
  jenkins-x.yml
Labels: approved, size/XS

#94 fix: Run BDD tests against a fresh cluster for bdd-jx PRs
  jenkins-x-release.yml
  jenkins-x.yml
  jx/bdd/README.md
  jx/bdd/ci.sh
  jx/bdd/cluster.yaml
  jx/bdd/jx-requirements.yml
  jx/bdd/parameters.yaml
Labels: approved, lgtm, size/L

#92 chore: parameterized jx ui app version
  test/suite/apps/helpers.go
Labels: approved, lgtm, size/XS

#91 feat(prow): Add tests for wip and hold plugins
  go.mod
  go.sum
  test/helpers/suite.go
  test/helpers/test.go
  test/suite/devpods/jx_devpod.go
  test/suite/ingress/jx_upgrade_ingress.go
  test/suite/platform/jx_upgrade_platform.go
  test/suite/quickstart/helpers.go
Labels: approved, lgtm, size/XL

#90 feat(prow): Add BDD tests for ChatOps commands
  test/suite/quickstart/helpers.go
Labels: approved, lgtm, size/XS
