Repository jenkins-x/bdd-jx, pull requests merged in 2019-12, with the labels that each got.

#98 Add Daniel to owners
  OWNERS
Labels: approved, size/XS

#96 feat: E2E tests for jx upgrade boot
  Makefile
  test/helpers/test.go
  test/suite/apps/helpers.go
  test/suite/apps/ui.go
  test/suite/upgrade/upgrade_boot.go
  test/suite/upgrade/upgrade_boot_test.go
Labels: lgtm, size/L

#99 chore: make the upgrade ref and binary overwrite
  jenkins-x.yml
  jx/bdd/ci.sh
  test/suite/upgrade/upgrade_boot.go
Labels: approved, lgtm, size/S

#101 chore: add romain to approvers
  OWNERS
Labels: approved, lgtm, size/XS

#100 Jxui dev mode
  .gitignore
  test/suite/jxui/Readme.md
  test/suite/jxui/jxui.go
  test/utils/runner/runner.go
Labels: approved, lgtm, size/L

#102 chore: reorganise jxui test code
  test/suite/jxui/jxui.go
Labels: approved, lgtm, size/L

#103 chore: move screenshots in test report dir
  test/suite/jxui/ui-smoke/run.sh
Labels: approved, lgtm, size/XS
