Repository jenkins-x/bdd-jx, pull requests merged in 2020-06, with the labels that each got.

#159 feat: Support basic auth protected JXUI
  test/suite/jxui/jxui.go
  test/suite/jxui/ui-smoke/cypress/integration/smoke.spec.js
  test/suite/jxui/ui-smoke/get-free-port.js
  test/suite/jxui/ui-smoke/package-lock.json
  test/suite/jxui/ui-smoke/package.json
  test/suite/jxui/ui-smoke/proxy.js
  test/suite/jxui/ui-smoke/run.sh
Labels: approved, lgtm, size/XXL

#160 fix: Support basic auth with UI for apps test as well
  OWNERS
  test/helpers/test.go
  test/suite/apps/ui.go
  test/suite/jxui/jxui.go
Labels: approved, lgtm, size/M

#161 fix: assume jxui basic auth by default
  test/suite/jxui/jxui.go
Labels: approved, lgtm, size/XS

#162 chore: Add test for OWNERS link in Lighthouse
  test/helpers/test.go
  test/suite/lighthouse/helpers.go
Labels: approved, lgtm, size/M

#164 chore: Add make commands for single quickstart/import tests
  Makefile
Labels: approved, lgtm, size/S
