Repository jenkins-x/bdd-jx, pull requests merged in 2020-04, with the labels that each got.

#143 chore: Prepare for Golang 1.13
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#144 chore: Add testing of Lighthouse status report link
  test/helpers/suite.go
  test/helpers/test.go
Labels: approved, lgtm, size/S

#145 fix: Forgot about pointers
  test/helpers/test.go
Labels: approved, lgtm, size/XS

#146 chore: update tests for new lighthouse configuration
  test/suite/saas/jx_saas.go
Labels: size/S

#149 fix: failing test for ui
  test/suite/apps/ui.go
  test/suite/jxui/jxui.go
Labels: approved, lgtm, size/XS

#148 fix: Get Lighthouse tests to work on GitLab
  go.mod
  go.sum
  jx/bdd/ci.sh
  test/helpers/test.go
  test/suite/lighthouse/helpers.go
  test/suite/saas/jx_saas.go
Labels: approved, lgtm, size/L
