Repository jenkins-x/bdd-jx, pull requests merged in 2020-02, with the labels that each got.

#113 chore: logging the credentials file to the screen
  Makefile
Labels: approved, lgtm, size/XS

#115 feat: setting some git debugging variables
  Makefile
Labels: approved, lgtm, size/XS

#118 chore: setting XDG_CONFIG_HOME for release and pr pipeline
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#114 fix: Test for PR PipelineActivity being populated by build controller
  test/helpers/test.go
Labels: approved, lgtm, size/M

#116 chore: change where variables are being set
  Makefile
  jx/bdd/ci.sh
Labels: approved, lgtm, size/XS

#119 feat: stop setting the credentials helper to store
  Makefile
Labels: size/XS

#120 revert: stop setting the credentials helper to store
  Makefile
Labels: size/XS

#121 chore: generate the .gitcredentials file in the /root dir
  Makefile
Labels: size/XS

#122 fix: revert writing credentials to /root dir
  Makefile
Labels: size/XS

#123 chore: remove extra debug commands
  Makefile
Labels: size/XS

#126 fix: Allow disabling PipelineActivity update check
  test/helpers/suite.go
  test/helpers/test.go
Labels: approved, lgtm, size/S

#127 test: update search test to match the new behaviour
  OWNERS
  test/suite/jxui/ui-smoke/cypress/integration/smoke.spec.js
Labels: approved, lgtm, size/S

#124 chore: remove dependency on jx/util package
  go.sum
  test/suite/ingress/jx_upgrade_ingress.go
  test/utils/color.go
  test/utils/suggestions.go
  test/utils/utils.go
Labels: lgtm, size/L

#80 fix: Turn check that activity is successful back on
  test/helpers/test.go
Labels: approved, lgtm, size/S

#128 chore: improved error message of saas pod check
  test/suite/saas/jx_saas.go
Labels: approved, lgtm, size/XS

#46 fix: we were ignoring the err on the http code check
  test/helpers/test.go
Labels: approved, lgtm, size/XS

#129 chore: re-enable nexus ingress checks
  test/suite/saas/jx_saas.go
Labels: approved, lgtm, size/S

#130 fix: upgrade to latest jx
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#131 fix: add a `testbin` goal to create a bddjx binary
  Makefile
Labels: approved, lgtm, size/XS

#133 fix: update build search test to no validate the exact number of builds filtered
  test/suite/jxui/ui-smoke/cypress/integration/smoke.spec.js
Labels: lgtm, size/XS
