Repository jenkins-x/bdd-jx, pull requests merged in 2020-03, with the labels that each got.

#134 fix: Tide should be merging PRs we have been merging manually in tests
  jx/bdd/jx-requirements.yml
  jx/bdd/parameters.yaml
  test/helpers/test.go
  test/suite/apps/ui.go
  test/suite/jxui/jxui.go
  test/utils/parsers/create_pull_request_parser.go
Labels: approved, lgtm, size/L

#137 fix: ignore warning lines when getting applications
  test/utils/parsers/get_applications_parser.go
Labels: approved, size/XS

#136 fix: Use /approve for merging PRs
  jenkins-x.yml
  jx/bdd/jx-requirements.yml
  test/helpers/apps.go
  test/helpers/test.go
  test/suite/apps/ui.go
  test/suite/jxui/jxui.go
  test/suite/platform/jx_upgrade_platform.go
  test/suite/quickstart/helpers.go
  test/suite/saas/jx_saas.go
  test/suite/upgrade/upgrade_boot.go
Labels: approved, lgtm, size/L

#138 fix: Add Lighthouse/Prow test for retest and override
  Makefile
  go.sum
  test/helpers/test.go
  test/suite/lighthouse/helpers.go
  test/suite/lighthouse/lighthouse_test.go
  test/suite/quickstart/helpers.go
Labels: approved, lgtm, size/L

#139 chore: check the label does not contain jx-boot
  test/suite/saas/jx_saas.go
Labels: approved, lgtm, size/XS

#140 chore: adding option to force local git auth config service
  test/helpers/suite.go
  test/helpers/test.go
  test/suite/spring/jx_create_spring.go
Labels: approved, do-not-merge/hold, size/M

#141 chore: add a test to verify stackdriver on saas
  test/suite/saas/jx_saas.go
Labels: approved, lgtm, size/S

#142 chore: enable assertion on SaaS test for stackdriver logging
  test/suite/saas/jx_saas.go
Labels: approved, lgtm, size/XS
