Repository jenkins-x/bdd-jx, pull requests merged in 2020-01, with the labels that each got.

#104 chore: Update jx dependency, fix logic for secrets
  go.mod
  go.sum
  test/helpers/test.go
Labels: approved, lgtm, size/M

#105 feat: disable chatops commands testing
  Makefile
Labels: approved, lgtm, size/XS

#95 feat: disable the import with a jenkins-x file as it's hardcoded to push to GCR
  test/suite/_import/jx_import.go
Labels: approved, lgtm, size/XS

#106 fix(test): fix test related to PR-1140
  test/suite/jxui/ui-smoke/cypress/integration/smoke.spec.js
Labels: approved, lgtm, size/S

#107 chore: Enable chatops tests explicitly only
  go.mod
  go.sum
  test/helpers/suite.go
  test/helpers/test.go
Labels: approved, lgtm, size/S

#53 chore: added precommit configuration
  .pre-commit-config.yaml
  .secrets.baseline
Labels: approved, lgtm

#108 chore: displaying the git-credentials to the console
  Makefile
Labels: approved, lgtm, size/XS

#110 fix: Gitlab merge request URL format has changed
  test/utils/parsers/create_pull_request_parser.go
Labels: approved, lgtm, size/XS

#111 fix: Don't just parse app URL, check for non-empty scheme
  test/utils/parsers/get_applications_parser.go
Labels: approved, lgtm, size/XS

#112 feat: allow the test suite to be configured as an env var
  Makefile
Labels: approved, lgtm, size/XS
